version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=newsletter_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
      - MAILER_URL=smtp://smtp.gmail.com:587
      - MAILER_ENCRYPTION=tls
      - MAILER_USER=myemail@gmail.com
      - MAILER_PASSWORD=mypassword
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=newsletter_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
    networks:
      - mynetwork

networks:
  mynetwork:
    external:
      name: mynetwork
