version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=newsletter_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
      - MAILER_URL=smtp://smtp.gmail.com:587
      - MAILER_ENCRYPTION=tls
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=newsletter_db
      - MYSQL_PASSWORD=""
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
